name: GitHub-Profile-Summary-Cards

on:
  create:
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-cards
    permissions:
      contents: write
  
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
      - name: Download Image
        run: |
          mkdir -p github-profile-trophy
          curl -o github-profile-trophy/github-profile-trophy.svg "https://github-profile-trophy.morteza-karimi.ir/?username=mortezakarimi&column=11&theme=darkhub&margin-w=15&margin-h=15"
          
          mkdir -p readme-states
          curl -o readme-states/readme-states.svg "https://readme-states.morteza-karimi.ir/api?username=mortezakarimi&count_private=true&include_all_commits=true&theme=github_dark&show_icons=true&custom_title=Stats&show=reviews,prs_merged,prs_merged_percentage"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/image.jpg
          git commit -m "Add downloaded image" || echo "No changes to commit"
          git push
